module.exports = {
  apps: [
    {
      name: 'corta-precos-server',
      script: 'server.js',
      cwd: '/workspace/project',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: '8011' },
      watch: false,
      autorestart: true,
      restart_delay: 2000,
      max_restarts: 50,
      min_uptime: '5s',
      log_file: '/tmp/cp-server.log',
      error_file: '/tmp/cp-server-err.log',
      out_file: '/tmp/cp-server-out.log',
      merge_logs: true,
    },
    {
      name: 'corta-precos-tunnel',
      script: '/tmp/cloudflared',
      args: 'tunnel --url http://localhost:8011 --no-autoupdate',
      cwd: '/workspace/project',
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      min_uptime: '5s',
      log_file: '/tmp/cp-tunnel.log',
      error_file: '/tmp/cp-tunnel-err.log',
      out_file: '/tmp/cp-tunnel-out.log',
      merge_logs: true,
    },
  ],
}
